package com.jamesr.gtbsolver;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;

@Mod(modid = GTBSolver.MODID, version = GTBSolver.VERSION)

public class GTBSolver {

    public static final String MODID = "gtbsolver";
    public static final String VERSION = "1.0";
    
    public static HashMap<Integer, ArrayList<String>> words;
    
    @EventHandler
    public void init(FMLInitializationEvent event) {
    	
    	MinecraftForge.EVENT_BUS.register(this);
    	ClientCommandHandler.instance.registerCommand(new GTBCommand());
    	
    	words = new HashMap<Integer, ArrayList<String>>();
    	
        addWord("abandoned mansion");
        addWord("abonded mansion");
        addWord("advent calendar");
        addWord("air horn");
        addWord("airplane");
        addWord("airport");
        addWord("airship");
        addWord("aladdin");
        addWord("alarm");
        addWord("alarm clock");
        addWord("alien");
        addWord("ambulance");
        addWord("america");
        addWord("american football");
        addWord("anchor");
        addWord("angel");
        addWord("angry");
        addWord("animal");
        addWord("animals");
        addWord("ant");
        addWord("anvil");
        addWord("ape");
        addWord("apocalypse");
        addWord("apple");
        addWord("apple pie");
        addWord("apple tree");
        addWord("aquarium");
        addWord("arcade");
        addWord("arcade game");
        addWord("arcade machine");
        addWord("archer");
        addWord("archery");
        addWord("arm");
        addWord("armor");
        addWord("army");
        addWord("arrow");
        addWord("art");
        addWord("artist");
        addWord("astronaut");
        addWord("atmosphere");
        addWord("australia");
        addWord("automobile");
        addWord("autumn");
        addWord("avocado");
        addWord("award");
        addWord("awards");
        addWord("axe");
        addWord("bbq grill");
        addWord("baby");
        addWord("backflip");
        addWord("backpack");
        addWord("bacon");
        addWord("badge");
        addWord("badminton");
        addWord("bag");
        addWord("baguette");
        addWord("baker");
        addWord("bakery");
        addWord("baking");
        addWord("balance beam");
        addWord("bald head");
        addWord("balloon");
        addWord("balloons");
        addWord("bamboo");
        addWord("banana");
        addWord("banana peel");
        addWord("band");
        addWord("band aid");
        addWord("bandage");
        addWord("banjo");
        addWord("bank");
        addWord("banner");
        addWord("bar");
        addWord("barbeque");
        addWord("barcode");
        addWord("barn");
        addWord("barrel");
        addWord("barrier");
        addWord("baseball");
        addWord("baseball bat");
        addWord("baseball field");
        addWord("basilisk");
        addWord("basket");
        addWord("basket ball");
        addWord("basketball");
        addWord("basketball court");
        addWord("basketball hoop");
        addWord("bat");
        addWord("bath");
        addWord("bath tub");
        addWord("bathroom");
        addWord("batman");
        addWord("battering ram");
        addWord("battery");
        addWord("battle axe");
        addWord("battleship");
        addWord("bay");
        addWord("beach");
        addWord("beach ball");
        addWord("beach party");
        addWord("bean");
        addWord("bean bag");
        addWord("beanie");
        addWord("beans");
        addWord("beanstalk");
        addWord("bear");
        addWord("beard");
        addWord("beaver");
        addWord("bed");
        addWord("bedroom");
        addWord("bedtime");
        addWord("bee");
        addWord("beef");
        addWord("beehive");
        addWord("beetle");
        addWord("bell");
        addWord("belt");
        addWord("bench");
        addWord("berries");
        addWord("berry");
        addWord("bicycle");
        addWord("big ben");
        addWord("bigfoot");
        addWord("bike");
        addWord("bike riding");
        addWord("bill board");
        addWord("billboard");
        addWord("bin");
        addWord("bingo");
        addWord("binoculars");
        addWord("biology");
        addWord("bird");
        addWord("bird nest");
        addWord("bird feeder");
        addWord("birdbath");
        addWord("birdcage");
        addWord("birds");
        addWord("birthday");
        addWord("birthday cake");
        addWord("birthday party");
        addWord("biscuit");
        addWord("black hole");
        addWord("blackboard");
        addWord("blanket");
        addWord("blaze");
        addWord("blender");
        addWord("blimp");
        addWord("blizzard");
        addWord("blocks");
        addWord("board game");
        addWord("boat");
        addWord("bobsledding");
        addWord("bodyguard");
        addWord("bomb");
        addWord("bone");
        addWord("book");
        addWord("book shelf");
        addWord("bookcase");
        addWord("bookmark");
        addWord("bookshelf");
        addWord("bookstore");
        addWord("boom box");
        addWord("boomerang");
        addWord("boots");
        addWord("border");
        addWord("bottle");
        addWord("bounce");
        addWord("bouncy castle");
        addWord("bow");
        addWord("bow tie");
        addWord("bow and arrow");
        addWord("bowl");
        addWord("bowling");
        addWord("bowling alley");
        addWord("bowling ball");
        addWord("bowling pin");
        addWord("bowtie");
        addWord("box");
        addWord("box of chocolates");
        addWord("box of chocolate");
        addWord("boxing");
        addWord("boxing gloves");
        addWord("boxing ring");
        addWord("boy");
        addWord("bracelet");
        addWord("brain");
        addWord("branch");
        addWord("bread");
        addWord("breakfast");
        addWord("breakfast in bed");
        addWord("brick");
        addWord("bridge");
        addWord("broccoli");
        addWord("broken");
        addWord("broom");
        addWord("broomstick");
        addWord("brush");
        addWord("bubble");
        addWord("bubble bath");
        addWord("bubbles");
        addWord("bucket");
        addWord("buffet");
        addWord("bug");
        addWord("build battle");
        addWord("builder");
        addWord("building");
        addWord("bull");
        addWord("bulldozer");
        addWord("bullet");
        addWord("bumblebee");
        addWord("bumper cars");
        addWord("bunk bed");
        addWord("bunny");
        addWord("burger");
        addWord("bus");
        addWord("bus stop");
        addWord("bush");
        addWord("butcher");
        addWord("butter");
        addWord("butterfly");
        addWord("button");
        addWord("cab");
        addWord("cabbage");
        addWord("cabin");
        addWord("cabinet");
        addWord("cable");
        addWord("cactus");
        addWord("cage");
        addWord("cake");
        addWord("calculator");
        addWord("calendar");
        addWord("camel");
        addWord("camera");
        addWord("camouflage");
        addWord("camp");
        addWord("campfire");
        addWord("campground");
        addWord("camping");
        addWord("can");
        addWord("canada");
        addWord("canal");
        addWord("candle");
        addWord("candy");
        addWord("candy cane");
        addWord("cane");
        addWord("cannon");
        addWord("cannonball");
        addWord("canoe");
        addWord("canopy bed");
        addWord("cap");
        addWord("cape");
        addWord("car");
        addWord("carolling");
        addWord("car park");
        addWord("car wash");
        addWord("caravan");
        addWord("card");
        addWord("card games");
        addWord("cardboard box");
        addWord("cards");
        addWord("caribbean");
        addWord("carnival");
        addWord("carpenter");
        addWord("carpet");
        addWord("carriage");
        addWord("carrot");
        addWord("carrots");
        addWord("cart");
        addWord("cartoon");
        addWord("cartwheel");
        addWord("cash");
        addWord("cash register");
        addWord("cashier");
        addWord("cassette");
        addWord("castle");
        addWord("cat");
        addWord("catacomb");
        addWord("catapult");
        addWord("caterpillar");
        addWord("cauliflower");
        addWord("cauldron");
        addWord("cave");
        addWord("ceiling");
        addWord("ceiling fan");
        addWord("celebrate");
        addWord("cell");
        addWord("cellphone");
        addWord("cellphone charger");
        addWord("centaur");
        addWord("cereal");
        addWord("chain");
        addWord("chainsaw");
        addWord("chair");
        addWord("chairs");
        addWord("chalk");
        addWord("chameleon");
        addWord("charger");
        addWord("cheating");
        addWord("checkerboard");
        addWord("cheese");
        addWord("cheeseburger");
        addWord("cheesecake");
        addWord("chef");
        addWord("chefs hat");
        addWord("chemistry");
        addWord("cherries");
        addWord("cherry");
        addWord("chess");
        addWord("chess piece");
        addWord("chest");
        addWord("chestnut");
        addWord("chestplate");
        addWord("chicken");
        addWord("chicken fingers");
        addWord("chicken jockey");
        addWord("chicken nugget");
        addWord("chihuahua");
        addWord("chili pepper");
        addWord("chilli");
        addWord("chimney");
        addWord("china");
        addWord("chip");
        addWord("chocolate");
        addWord("chocolate bar");
        addWord("chocolate cake");
        addWord("chocolate chip cookie");
        addWord("chocolate factory");
        addWord("chocolate milk");
        addWord("chopsticks");
        addWord("christmas");
        addWord("christmas card");
        addWord("christmas tree");
        addWord("christmas cracker");
        addWord("christmas lights");
        addWord("church");
        addWord("cinema");
        addWord("circle");
        addWord("circus");
        addWord("city building");
        addWord("clam");
        addWord("clap");
        addWord("class");
        addWord("classroom");
        addWord("claw");
        addWord("clay");
        addWord("cliff");
        addWord("climbing");
        addWord("climbing boots");
        addWord("climbing frame");
        addWord("cloak");
        addWord("clock");
        addWord("clock tower");
        addWord("closet");
        addWord("clouds");
        addWord("clown");
        addWord("clown fish");
        addWord("coat");
        addWord("coal");
        addWord("coat hanger");
        addWord("cobweb");
        addWord("cockroach");
        addWord("coconut");
        addWord("cocoon");
        addWord("coffee");
        addWord("coffee cup");
        addWord("coffee table");
        addWord("coffee machine");
        addWord("coffin");
        addWord("cog");
        addWord("coin");
        addWord("coins");
        addWord("colored pencil");
        addWord("comb");
        addWord("comedy");
        addWord("comet");
        addWord("comic book");
        addWord("compass");
        addWord("compost bin");
        addWord("computer");
        addWord("computer desk");
        addWord("computer keyboard");
        addWord("computer mouse");
        addWord("computer monitor");
        addWord("computer screen");
        addWord("concert");
        addWord("console games");
        addWord("construction");
        addWord("construction yard");
        addWord("contestant");
        addWord("controller");
        addWord("conveyor belt");
        addWord("cook");
        addWord("cooker");
        addWord("cookie");
        addWord("cookie jar");
        addWord("cookie monster");
        addWord("cooking");
        addWord("corn");
        addWord("corn dog");
        addWord("corner");
        addWord("cornucopia");
        addWord("cotton candy");
        addWord("couch");
        addWord("cow");
        addWord("cowbell");
        addWord("cowboy");
        addWord("cowboy hat");
        addWord("crab");
        addWord("crane");
        addWord("crate");
        addWord("crater");
        addWord("crayon");
        addWord("credit card");
        addWord("creeper");
        addWord("crib");
        addWord("cricket");
        addWord("criminal");
        addWord("crocodile");
        addWord("cross country");
        addWord("crossbow");
        addWord("crosswalk");
        addWord("crow");
        addWord("crowbar");
        addWord("crown");
        addWord("cruise");
        addWord("cruise ship");
        addWord("cry");
        addWord("crystal");
        addWord("crystal ball");
        addWord("cube");
        addWord("cuckoo clock");
        addWord("cucumber");
        addWord("cup");
        addWord("cup of water");
        addWord("cupboard");
        addWord("cupcake");
        addWord("curtain");
        addWord("curtains");
        addWord("cushion");
        addWord("cycle");
        addWord("cyclone");
        addWord("cyclops");
        addWord("dj booth");
        addWord("dvd");
        addWord("dab");
        addWord("dad");
        addWord("daffodil");
        addWord("dagger");
        addWord("date");
        addWord("dance");
        addWord("dancefloor");
        addWord("dance competition");
        addWord("dancer");
        addWord("dancing");
        addWord("day");
        addWord("dead tree");
        addWord("deck of cards");
        addWord("decoration");
        addWord("decorations");
        addWord("deer");
        addWord("demon");
        addWord("dentist");
        addWord("dentures");
        addWord("deodorant");
        addWord("desert");
        addWord("deserted island");
        addWord("desk");
        addWord("dessert");
        addWord("devil");
        addWord("diamond");
        addWord("diamond ring");
        addWord("dice");
        addWord("dictator");
        addWord("dimples");
        addWord("dinner");
        addWord("dinner table");
        addWord("dinosaur");
        addWord("dirt house");
        addWord("disappear");
        addWord("disc");
        addWord("disco");
        addWord("disco ball");
        addWord("dish");
        addWord("dishes");
        addWord("dishwasher");
        addWord("dispenser");
        addWord("diving");
        addWord("diving board");
        addWord("doctor");
        addWord("dodgeball");
        addWord("dog");
        addWord("dog collar");
        addWord("dog walking");
        addWord("dogs");
        addWord("doll");
        addWord("dollar");
        addWord("dollhouse");
        addWord("dolphin");
        addWord("domino");
        addWord("donkey");
        addWord("donut");
        addWord("door");
        addWord("doorknob");
        addWord("dragon");
        addWord("dragon egg");
        addWord("dragonfly");
        addWord("drawing");
        addWord("dream");
        addWord("dress");
        addWord("dressing gown");
        addWord("drill");
        addWord("drink");
        addWord("drive through");
        addWord("driveway");
        addWord("droid");
        addWord("drum");
        addWord("drum sticks");
        addWord("drums");
        addWord("drumstick");
        addWord("duck");
        addWord("dumbbell");
        addWord("dungeon");
        addWord("dwarf");
        addWord("dye");
        addWord("dynamite");
        addWord("eagle");
        addWord("ear");
        addWord("earring");
        addWord("earth");
        addWord("easter");
        addWord("easter bunny");
        addWord("easter egg");
        addWord("ears");
        addWord("eating");
        addWord("eating competition");
        addWord("eclipse");
        addWord("eel");
        addWord("eggplant");
        addWord("eggs");
        addWord("eggs hatching");
        addWord("egypt");
        addWord("eiffel tower");
        addWord("elastic band");
        addWord("elbow");
        addWord("electricity");
        addWord("elephant");
        addWord("elevator");
        addWord("elf");
        addWord("elmo");
        addWord("emerald");
        addWord("emoji");
        addWord("enchant");
        addWord("ender dragon");
        addWord("enderman");
        addWord("energy");
        addWord("engine");
        addWord("england");
        addWord("envelope");
        addWord("environment");
        addWord("equestrian");
        addWord("eraser");
        addWord("escalator");
        addWord("esports");
        addWord("europe");
        addWord("examination");
        addWord("exercise");
        addWord("exit");
        addWord("experiment");
        addWord("explosion");
        addWord("eye");
        addWord("eye patch");
        addWord("eyebrow");
        addWord("eyes");
        addWord("face");
        addWord("factory");
        addWord("fair");
        addWord("fairground rides");
        addWord("fairy");
        addWord("fairytale");
        addWord("family");
        addWord("fan");
        addWord("fang");
        addWord("farm");
        addWord("farmer");
        addWord("farmhouse");
        addWord("farming");
        addWord("farmland");
        addWord("fast food");
        addWord("fat");
        addWord("feather");
        addWord("feet");
        addWord("fence");
        addWord("fencing");
        addWord("ferret");
        addWord("ferris wheel");
        addWord("ferry");
        addWord("festival");
        addWord("fez");
        addWord("fidget spinner");
        addWord("field");
        addWord("fight");
        addWord("fighter jet");
        addWord("fin");
        addWord("finger");
        addWord("finish line");
        addWord("fire");
        addWord("fire engine");
        addWord("fire extinguisher");
        addWord("fireball");
        addWord("firecracker");
        addWord("firefighter");
        addWord("firefly");
        addWord("fireplace");
        addWord("fireworks");
        addWord("first aid");
        addWord("fish");
        addWord("fish bowl");
        addWord("fish tank");
        addWord("fish and chips");
        addWord("fisherman");
        addWord("fishing");
        addWord("fishing rod");
        addWord("fist");
        addWord("flags");
        addWord("flame");
        addWord("flamingo");
        addWord("flare");
        addWord("flashlight");
        addWord("flat");
        addWord("fleece");
        addWord("flip phone");
        addWord("flipper");
        addWord("floating island");
        addWord("flood");
        addWord("floor");
        addWord("flowerbed");
        addWord("flowerpot");
        addWord("flowers");
        addWord("flute");
        addWord("fly");
        addWord("flying pig");
        addWord("fog");
        addWord("folder");
        addWord("food");
        addWord("foot");
        addWord("football");
        addWord("football field");
        addWord("footprint");
        addWord("forehead");
        addWord("forest");
        addWord("forest fire");
        addWord("fork");
        addWord("fortress");
        addWord("fortune cookie");
        addWord("fossil");
        addWord("fountain");
        addWord("four leaf clover");
        addWord("fox");
        addWord("frame");
        addWord("frankenstein");
        addWord("french flag");
        addWord("french fries");
        addWord("fridge");
        addWord("frisbee");
        addWord("frog");
        addWord("front porch");
        addWord("frown");
        addWord("fruit");
        addWord("fruit basket");
        addWord("fruit salad");
        addWord("frying pan");
        addWord("fudge");
        addWord("fun park");
        addWord("funhouse");
        addWord("fur");
        addWord("furnace");
        addWord("furniture");
        addWord("futuristic house");
        addWord("galaxy");
        addWord("game");
        addWord("games controller");
        addWord("gaming chair");
        addWord("gaming console");
        addWord("garage");
        addWord("garbage");
        addWord("garbage can");
        addWord("garbage truck");
        addWord("garden");
        addWord("garden furniture");
        addWord("garden hose");
        addWord("garden party");
        addWord("garden shed");
        addWord("gardening");
        addWord("garlic bread");
        addWord("gas mask");
        addWord("gates");
        addWord("genie");
        addWord("genie lamp");
        addWord("german flag");
        addWord("geyser");
        addWord("ghast");
        addWord("ghost");
        addWord("giant");
        addWord("gift");
        addWord("gifts");
        addWord("gingerbread man");
        addWord("gingerbread house");
        addWord("giraffe");
        addWord("girl");
        addWord("glass");
        addWord("glass door");
        addWord("glass table");
        addWord("glass of milk");
        addWord("glasses");
        addWord("globe");
        addWord("gloves");
        addWord("glue");
        addWord("gnome");
        addWord("go karting");
        addWord("goal");
        addWord("goalkeeper");
        addWord("goat");
        addWord("goblet");
        addWord("goblin");
        addWord("godzilla");
        addWord("goggles");
        addWord("gold");
        addWord("gold medal");
        addWord("gold mine");
        addWord("gold ring");
        addWord("golden apple");
        addWord("goldfish");
        addWord("golem");
        addWord("golf");
        addWord("golf cart");
        addWord("golf club");
        addWord("golf course");
        addWord("goose");
        addWord("gorilla");
        addWord("graduation");
        addWord("grand canyon");
        addWord("grandfather clock");
        addWord("grapes");
        addWord("graph");
        addWord("grappling hook");
        addWord("grasshopper");
        addWord("grassland");
        addWord("grave");
        addWord("gravel");
        addWord("gravestone");
        addWord("graveyard");
        addWord("great britain");
        addWord("green");
        addWord("greenhouse");
        addWord("grenade");
        addWord("guard dog");
        addWord("guardian");
        addWord("guitar");
        addWord("gum");
        addWord("gumball");
        addWord("gun");
        addWord("gym");
        addWord("gymnast");
        addWord("gymnastic rings");
        addWord("hair");
        addWord("hair band");
        addWord("hair brush");
        addWord("hair dye");
        addWord("hairbrush");
        addWord("haircut");
        addWord("hairdressers");
        addWord("hairdryer");
        addWord("hairspray");
        addWord("halloween");
        addWord("hallway");
        addWord("halo");
        addWord("ham");
        addWord("hamburger");
        addWord("hammer");
        addWord("hammock");
        addWord("hamster");
        addWord("hand");
        addWord("handbag");
        addWord("handcuffs");
        addWord("handgliding");
        addWord("hanggliding");
        addWord("handshake");
        addWord("handstand");
        addWord("happy");
        addWord("harbor");
        addWord("harmonica");
        addWord("harp");
        addWord("harry potter");
        addWord("hat");
        addWord("haunted house");
        addWord("hay");
        addWord("head");
        addWord("headband");
        addWord("headphones");
        addWord("headset");
        addWord("heart");
        addWord("heaven");
        addWord("hedge");
        addWord("hedgehog");
        addWord("helicopter");
        addWord("helipad");
        addWord("helmet");
        addWord("hen");
        addWord("heptagon");
        addWord("hero");
        addWord("hexagon");
        addWord("hide and seek");
        addWord("high heels");
        addWord("highway");
        addWord("hill");
        addWord("hippopotamus");
        addWord("hockey");
        addWord("hockey rink");
        addWord("hog");
        addWord("hole");
        addWord("holiday");
        addWord("holiday lights");
        addWord("hollywood sign");
        addWord("home");
        addWord("homework");
        addWord("honey");
        addWord("honeybee");
        addWord("honeycomb");
        addWord("hook");
        addWord("horn");
        addWord("horse");
        addWord("horse racing");
        addWord("horse riding");
        addWord("hospital");
        addWord("hot air balloon");
        addWord("hot chocolate");
        addWord("hot dog");
        addWord("hot tub");
        addWord("hotel");
        addWord("hourglass");
        addWord("house");
        addWord("hula hoop");
        addWord("hunger games");
        addWord("hunter");
        addWord("hurdles");
        addWord("hurricane");
        addWord("hut");
        addWord("hype train");
        addWord("hypixel");
        addWord("hypixel logo");
        addWord("hypnotize");
        addWord("ice bucket");
        addWord("ice castle");
        addWord("ice cream");
        addWord("ice cream cone");
        addWord("ice cream van");
        addWord("ice cube");
        addWord("ice skates");
        addWord("ice spike");
        addWord("ice skating");
        addWord("iceberg");
        addWord("icicle");
        addWord("icy");
        addWord("igloo");
        addWord("indiana jones");
        addWord("ink");
        addWord("insect");
        addWord("instrument");
        addWord("iron");
        addWord("ironing board");
        addWord("ironman");
        addWord("island");
        addWord("jacket");
        addWord("jail");
        addWord("japan");
        addWord("jar");
        addWord("javelin");
        addWord("jeans");
        addWord("jelly");
        addWord("jellybeans");
        addWord("jellyfish");
        addWord("jet ski");
        addWord("jetpack");
        addWord("jewel");
        addWord("jewellery");
        addWord("jigsaw");
        addWord("jogging");
        addWord("joystick");
        addWord("judgement");
        addWord("judo");
        addWord("juggler");
        addWord("juggling");
        addWord("juice");
        addWord("jump rope");
        addWord("jumping");
        addWord("jungle");
        addWord("kangaroo");
        addWord("karate");
        addWord("katana");
        addWord("kayak");
        addWord("kennel");
        addWord("ketchup");
        addWord("kettle");
        addWord("key");
        addWord("keys");
        addWord("kid");
        addWord("king");
        addWord("king kong");
        addWord("kiss");
        addWord("kitchen");
        addWord("kite");
        addWord("kitten");
        addWord("kiwi fruit");
        addWord("knee");
        addWord("knife");
        addWord("knight");
        addWord("knitting");
        addWord("koala");
        addWord("label");
        addWord("laboratory");
        addWord("ladder");
        addWord("ladybird");
        addWord("ladybug");
        addWord("lake");
        addWord("lamb");
        addWord("lamp");
        addWord("lamp post");
        addWord("lampshade");
        addWord("landscape");
        addWord("lantern");
        addWord("laptop");
        addWord("laser");
        addWord("lasso");
        addWord("latin");
        addWord("laughing");
        addWord("laundry basket");
        addWord("lava");
        addWord("lava bucket");
        addWord("lawn mower");
        addWord("lawyer");
        addWord("lead");
        addWord("leaf");
        addWord("leaking roof");
        addWord("leather");
        addWord("leaves");
        addWord("leg");
        addWord("legend of zelda");
        addWord("lemon");
        addWord("lemonade");
        addWord("lemonade stand");
        addWord("leprechaun");
        addWord("letter");
        addWord("lettuce");
        addWord("librarian");
        addWord("library");
        addWord("lifejacket");
        addWord("light");
        addWord("light switch");
        addWord("lightbulb");
        addWord("lighthouse");
        addWord("lightning");
        addWord("lightning bolt");
        addWord("lightning strike");
        addWord("lights");
        addWord("lightsaber");
        addWord("lilypad");
        addWord("lime");
        addWord("line");
        addWord("lion");
        addWord("lips");
        addWord("lipstick");
        addWord("litter");
        addWord("living room");
        addWord("lizard");
        addWord("llama");
        addWord("loaf of bread");
        addWord("lobster");
        addWord("loch ness monster");
        addWord("lock");
        addWord("lock pick");
        addWord("log");
        addWord("log cabin");
        addWord("lollipop");
        addWord("london");
        addWord("luggage");
        addWord("luigi");
        addWord("lumberjack");
        addWord("lump of coal");
        addWord("lunch");
        addWord("lunchbox");
        addWord("mp3 player");
        addWord("machine");
        addWord("mad scientist");
        addWord("magazine");
        addWord("magic");
        addWord("magic carpet");
        addWord("magic hat");
        addWord("magic trick");
        addWord("magic wand");
        addWord("magician");
        addWord("magma cube");
        addWord("magnet");
        addWord("magnifying glass");
        addWord("mail");
        addWord("mailbox");
        addWord("mailman");
        addWord("makeup");
        addWord("mammoth");
        addWord("mansion");
        addWord("map");
        addWord("marbles");
        addWord("mario");
        addWord("mark");
        addWord("marker");
        addWord("market");
        addWord("mars");
        addWord("marshmallow");
        addWord("mask");
        addWord("matchstick");
        addWord("math");
        addWord("mathematics");
        addWord("mattress");
        addWord("mayonnaise");
        addWord("maze");
        addWord("measurement");
        addWord("meatball");
        addWord("mechanic");
        addWord("medieval house");
        addWord("meeting");
        addWord("melon");
        addWord("mermaid");
        addWord("metal detector");
        addWord("meteorite");
        addWord("mexico");
        addWord("microphone");
        addWord("microwave");
        addWord("milk");
        addWord("milkshake");
        addWord("milky way");
        addWord("milk and cookies");
        addWord("mine");
        addWord("minecart");
        addWord("minecraft");
        addWord("miner");
        addWord("mineshaft");
        addWord("mini golf");
        addWord("mining");
        addWord("minion");
        addWord("mirror");
        addWord("missile");
        addWord("mistletoe");
        addWord("mittens");
        addWord("moat");
        addWord("mobility scooter");
        addWord("modern art");
        addWord("modern house");
        addWord("mole");
        addWord("mom");
        addWord("money");
        addWord("monitor");
        addWord("monkey");
        addWord("monsters");
        addWord("moon");
        addWord("moose");
        addWord("mop");
        addWord("morning");
        addWord("motorbike");
        addWord("mountain");
        addWord("mouse");
        addWord("mouse pad");
        addWord("mousepad");
        addWord("mousetrap");
        addWord("moustache");
        addWord("mouth");
        addWord("movie");
        addWord("movie scene");
        addWord("movie theatre");
        addWord("mud");
        addWord("muffin");
        addWord("mug");
        addWord("mummy");
        addWord("muscle");
        addWord("museum");
        addWord("mushroom");
        addWord("music");
        addWord("music note");
        addWord("musical");
        addWord("musical keyboard");
        addWord("musician");
        addWord("mustard");
        addWord("mystery box");
        addWord("nachos");
        addWord("naughty list");
        addWord("nail");
        addWord("nail polish");
        addWord("name tag");
        addWord("napkin");
        addWord("nature");
        addWord("necklace");
        addWord("needle");
        addWord("nether");
        addWord("newspaper");
        addWord("night");
        addWord("nightmare");
        addWord("ninja");
        addWord("ninja turtles");
        addWord("nintendo");
        addWord("nose");
        addWord("nosebleed");
        addWord("notepad");
        addWord("north pole");
        addWord("nurse");
        addWord("nutcracker");
        addWord("oar");
        addWord("oasis");
        addWord("ocean");
        addWord("ocelot");
        addWord("octagon");
        addWord("octopus");
        addWord("office");
        addWord("ogre");
        addWord("oil");
        addWord("olympics");
        addWord("omelette");
        addWord("onesie");
        addWord("onion ring");
        addWord("orange");
        addWord("orange juice");
        addWord("orchard");
        addWord("ore");
        addWord("organ");
        addWord("ornament");
        addWord("ostrich");
        addWord("otter");
        addWord("oven");
        addWord("owl");
        addWord("oxygen");
        addWord("oyster");
        addWord("pack of cards");
        addWord("package");
        addWord("packet");
        addWord("pacman");
        addWord("padlock");
        addWord("paint");
        addWord("paint bucket");
        addWord("paint palette");
        addWord("paintball");
        addWord("paintbrush");
        addWord("painter");
        addWord("painting");
        addWord("palace");
        addWord("palette");
        addWord("palm tree");
        addWord("pan");
        addWord("pancake");
        addWord("panda");
        addWord("paper");
        addWord("paper airplane");
        addWord("paperclip");
        addWord("parachute");
        addWord("park");
        addWord("parking");
        addWord("parkour");
        addWord("parrot");
        addWord("party");
        addWord("party hat");
        addWord("party popper");
        addWord("pathway");
        addWord("patio");
        addWord("pattern");
        addWord("paws");
        addWord("pea");
        addWord("peach");
        addWord("peacock");
        addWord("peanut");
        addWord("peanut butter");
        addWord("pear");
        addWord("pearl");
        addWord("pedals");
        addWord("pen");
        addWord("penalty");
        addWord("pencil");
        addWord("pencil case");
        addWord("pencil holder");
        addWord("penguin");
        addWord("pentagon");
        addWord("perfume");
        addWord("pet");
        addWord("pharaoh");
        addWord("phoenix");
        addWord("phone");
        addWord("phone case");
        addWord("phone charger");
        addWord("photoframe");
        addWord("photograph");
        addWord("photographer");
        addWord("piano");
        addWord("pickaxe");
        addWord("pickle");
        addWord("picture");
        addWord("picture frame");
        addWord("pie");
        addWord("pier");
        addWord("pig");
        addWord("pigeon");
        addWord("piggy bank");
        addWord("pigman");
        addWord("pikachu");
        addWord("pillow");
        addWord("pillowcase");
        addWord("pin");
        addWord("pinata");
        addWord("pine tree");
        addWord("pineapple");
        addWord("pineapple pizza");
        addWord("pinecone");
        addWord("ping pong");
        addWord("ping pong table");
        addWord("pipe");
        addWord("pirate");
        addWord("pirate hat");
        addWord("pirate ship");
        addWord("piston");
        addWord("pitchfork");
        addWord("pixel art");
        addWord("pizza");
        addWord("planet");
        addWord("plank");
        addWord("plant");
        addWord("plant pot");
        addWord("plate");
        addWord("platform");
        addWord("platypus");
        addWord("playground");
        addWord("playing cards");
        addWord("pliers");
        addWord("plug");
        addWord("plunger");
        addWord("pocket watch");
        addWord("podium");
        addWord("pogo stick");
        addWord("poison");
        addWord("pokeball");
        addWord("pokemon");
        addWord("polar bear");
        addWord("pole vault");
        addWord("police");
        addWord("police car");
        addWord("policecar");
        addWord("police officer");
        addWord("police station");
        addWord("policeman");
        addWord("pond");
        addWord("pong");
        addWord("pony");
        addWord("pool");
        addWord("pool table");
        addWord("poor");
        addWord("popcorn");
        addWord("poppy");
        addWord("popsicle");
        addWord("portal");
        addWord("post office");
        addWord("postcard");
        addWord("poster");
        addWord("pot");
        addWord("pot of gold");
        addWord("potato");
        addWord("potato chips");
        addWord("potatoes");
        addWord("potion");
        addWord("potted plant");
        addWord("power lines");
        addWord("power plug");
        addWord("present");
        addWord("presentation");
        addWord("pretzel");
        addWord("prince");
        addWord("princess");
        addWord("printer");
        addWord("prison");
        addWord("prison cell");
        addWord("prisoner");
        addWord("projectile");
        addWord("propeller");
        addWord("protest");
        addWord("pudding");
        addWord("puddle");
        addWord("pump");
        addWord("pumpkin");
        addWord("puppet");
        addWord("puppy");
        addWord("purse");
        addWord("puzzle");
        addWord("puzzle cube");
        addWord("pyjamas");
        addWord("pyramid");
        addWord("quad bike");
        addWord("queen");
        addWord("quicksand");
        addWord("quiver");
        addWord("rabbit");
        addWord("raccoon");
        addWord("race");
        addWord("race track");
        addWord("racecar");
        addWord("racehorse");
        addWord("radio");
        addWord("raft");
        addWord("railway");
        addWord("rain");
        addWord("rain coat");
        addWord("rainbow");
        addWord("raindrop");
        addWord("rake");
        addWord("rat");
        addWord("ravine");
        addWord("reading");
        addWord("reindeer");
        addWord("reaper");
        addWord("recycle");
        addWord("redstone");
        addWord("reef");
        addWord("refrigerator");
        addWord("remote");
        addWord("remote control");
        addWord("restaurant");
        addWord("rhino");
        addWord("ribbon");
        addWord("rice");
        addWord("rich");
        addWord("ride");
        addWord("ring");
        addWord("river");
        addWord("road");
        addWord("robin hood");
        addWord("robot");
        addWord("rock");
        addWord("rock band");
        addWord("rock climbing");
        addWord("rock and roll");
        addWord("rocket");
        addWord("rocket launcher");
        addWord("rocket ship");
        addWord("rocking chair");
        addWord("roller blades");
        addWord("rollercoaster");
        addWord("roof");
        addWord("room");
        addWord("rope");
        addWord("rose");
        addWord("rose bush");
        addWord("roundabout");
        addWord("rowboat");
        addWord("rowing");
        addWord("rubber");
        addWord("rubber band");
        addWord("rubber duck");
        addWord("rubbish");
        addWord("rubiks cube");
        addWord("rug");
        addWord("ruler");
        addWord("runner");
        addWord("running");
        addWord("sad");
        addWord("saddle");
        addWord("safe");
        addWord("safety goggles");
        addWord("sail");
        addWord("sailboat");
        addWord("sailing");
        addWord("sailing boat");
        addWord("salad");
        addWord("salamander");
        addWord("salmon");
        addWord("saloon");
        addWord("salt");
        addWord("salt and pepper");
        addWord("samurai");
        addWord("sand castle");
        addWord("sandbox");
        addWord("sandcastle");
        addWord("sandwiches");
        addWord("santa");
        addWord("santa workshop");
        addWord("santas workshop");
        addWord("santa claus");
        addWord("sardines");
        addWord("satellite");
        addWord("sauce");
        addWord("sausage");
        addWord("saw");
        addWord("saxophone");
        addWord("scaffold");
        addWord("scale");
        addWord("scarecrow");
        addWord("scared");
        addWord("scarf");
        addWord("school");
        addWord("school bus");
        addWord("science");
        addWord("scientist");
        addWord("scissors");
        addWord("scooby doo");
        addWord("scooter");
        addWord("scorpion");
        addWord("screen");
        addWord("screw");
        addWord("screwdriver");
        addWord("scuba diving");
        addWord("scythe");
        addWord("sea turtle");
        addWord("seafood");
        addWord("seagull");
        addWord("seahorse");
        addWord("seal");
        addWord("seat");
        addWord("seaweed");
        addWord("security camera");
        addWord("seed");
        addWord("seesaw");
        addWord("self portrait");
        addWord("sewing machine");
        addWord("sewer");
        addWord("shack");
        addWord("shampoo");
        addWord("shapes");
        addWord("shark");
        addWord("shaving");
        addWord("shed");
        addWord("sheep");
        addWord("sheet");
        addWord("shelf");
        addWord("shell");
        addWord("shelter");
        addWord("shield");
        addWord("ship");
        addWord("shipwreck");
        addWord("shirt");
        addWord("shoe laces");
        addWord("shopping");
        addWord("shoes");
        addWord("shop");
        addWord("shopping bag");
        addWord("shopping trolley");
        addWord("short");
        addWord("shorts");
        addWord("shoulder");
        addWord("shovel");
        addWord("shower");
        addWord("shrek");
        addWord("sidewalk");
        addWord("sign");
        addWord("signal");
        addWord("signpost");
        addWord("silo");
        addWord("singer");
        addWord("singing");
        addWord("sink");
        addWord("skateboarding");
        addWord("skatepark");
        addWord("skating");
        addWord("skating rink");
        addWord("skeleton");
        addWord("ski");
        addWord("ski lodge");
        addWord("skiing");
        addWord("skinny");
        addWord("skirt");
        addWord("skull");
        addWord("sky");
        addWord("skywars");
        addWord("skydiver");
        addWord("skyscraper");
        addWord("sleep");
        addWord("sled");
        addWord("sleeping");
        addWord("sleeping bag");
        addWord("sleigh");
        addWord("slide");
        addWord("slime");
        addWord("slippers");
        addWord("slope");
        addWord("sloth");
        addWord("slug");
        addWord("smartphone");
        addWord("smell");
        addWord("smelting");
        addWord("smile");
        addWord("smiley");
        addWord("smoke");
        addWord("smoking");
        addWord("smoothie");
        addWord("snail");
        addWord("snake");
        addWord("sneakers");
        addWord("sniper");
        addWord("snow");
        addWord("snowy forest");
        addWord("snowball fight");
        addWord("snowball");
        addWord("snowboarding");
        addWord("snowflake");
        addWord("snowing");
        addWord("snowman");
        addWord("snowy");
        addWord("snow globe");
        addWord("soap");
        addWord("soccer");
        addWord("soccer ball");
        addWord("social media");
        addWord("socks");
        addWord("soda");
        addWord("soda can");
        addWord("sofa");
        addWord("soil");
        addWord("solar panel");
        addWord("solar system");
        addWord("soldier");
        addWord("song");
        addWord("sound");
        addWord("soup");
        addWord("space");
        addWord("space invaders");
        addWord("spaceship");
        addWord("spade");
        addWord("spaghetti");
        addWord("spanner");
        addWord("sparkler");
        addWord("speakers");
        addWord("spear");
        addWord("speedboat");
        addWord("spell");
        addWord("sphere");
        addWord("spider");
        addWord("spider web");
        addWord("spiderman");
        addWord("spine");
        addWord("spleef");
        addWord("sponge");
        addWord("spongebob");
        addWord("spooky house");
        addWord("spoon");
        addWord("sports");
        addWord("spray");
        addWord("spring");
        addWord("sprinkler");
        addWord("sprint");
        addWord("spy");
        addWord("square");
        addWord("squid");
        addWord("squirrel");
        addWord("stables");
        addWord("stadium");
        addWord("stage");
        addWord("staircase");
        addWord("stairs");
        addWord("stamp");
        addWord("star");
        addWord("star wars");
        addWord("starfish");
        addWord("statue");
        addWord("steak");
        addWord("steam locomotive");
        addWord("steering wheel");
        addWord("step ladder");
        addWord("step stool");
        addWord("stepping stones");
        addWord("stereo");
        addWord("stick");
        addWord("sticky note");
        addWord("stingray");
        addWord("stocking");
        addWord("stop sign");
        addWord("stopwatch");
        addWord("storage");
        addWord("store");
        addWord("storm");
        addWord("stove");
        addWord("straw");
        addWord("strawberry");
        addWord("street");
        addWord("streetlamp");
        addWord("string");
        addWord("strong");
        addWord("submarine");
        addWord("sugar");
        addWord("suit");
        addWord("suitcase");
        addWord("summer");
        addWord("sumo");
        addWord("sun");
        addWord("sunbed");
        addWord("sunflower");
        addWord("sunglasses");
        addWord("sunken airplane");
        addWord("sunken ship");
        addWord("sunlight");
        addWord("sunrise");
        addWord("sunset");
        addWord("super hero");
        addWord("super mario");
        addWord("supermarket");
        addWord("surfboard");
        addWord("surfing");
        addWord("surgery");
        addWord("surprise");
        addWord("sushi");
        addWord("swamp");
        addWord("swan");
        addWord("sweater");
        addWord("swimming");
        addWord("swimming pool");
        addWord("swing");
        addWord("swiss cheese");
        addWord("switch");
        addWord("sword");
        addWord("swordfish");
        addWord("t-rex");
        addWord("t-shirt");
        addWord("tnt");
        addWord("tnt cannon");
        addWord("tv remote");
        addWord("table");
        addWord("table cloth");
        addWord("table tennis");
        addWord("tablet");
        addWord("tail");
        addWord("talent show");
        addWord("tall");
        addWord("tank");
        addWord("tape");
        addWord("target");
        addWord("tattoo");
        addWord("tavern");
        addWord("taxi");
        addWord("tea");
        addWord("tea and biscuits");
        addWord("teacup");
        addWord("teapot");
        addWord("tears");
        addWord("technology");
        addWord("teddy bear");
        addWord("teeth");
        addWord("telephone");
        addWord("telephone booth");
        addWord("telescope");
        addWord("television");
        addWord("temple");
        addWord("tennis");
        addWord("tennis ball");
        addWord("tennis court");
        addWord("tent");
        addWord("tetris");
        addWord("texting");
        addWord("thanksgiving");
        addWord("the end");
        addWord("the grinch");
        addWord("the hulk");
        addWord("the moon");
        addWord("the simpsons");
        addWord("theater");
        addWord("theme park");
        addWord("thermometer");
        addWord("thief");
        addWord("throne");
        addWord("thug");
        addWord("thumb");
        addWord("thunder");
        addWord("thunderstorm");
        addWord("tic tac toe");
        addWord("ticket");
        addWord("tie");
        addWord("tiger");
        addWord("tightrope");
        addWord("time");
        addWord("time machine");
        addWord("tin can");
        addWord("tinsel");
        addWord("tire swing");
        addWord("tissue");
        addWord("titanic");
        addWord("toad");
        addWord("toast");
        addWord("toaster");
        addWord("toes");
        addWord("toilet");
        addWord("toilet paper");
        addWord("tomato");
        addWord("tomato ketchup");
        addWord("tongue");
        addWord("tools");
        addWord("tooth");
        addWord("tooth fairy");
        addWord("toothbrush");
        addWord("toothless");
        addWord("toothpaste");
        addWord("top hat");
        addWord("torch");
        addWord("tornado");
        addWord("tortoise");
        addWord("totem pole");
        addWord("tow truck");
        addWord("towel");
        addWord("towel rack");
        addWord("tower");
        addWord("tower of pisa");
        addWord("toy");
        addWord("toy factory");
        addWord("toy soldier");
        addWord("toy story");
        addWord("track");
        addWord("tractor");
        addWord("trading");
        addWord("traffic");
        addWord("traffic jam");
        addWord("traffic lights");
        addWord("trailer");
        addWord("train station");
        addWord("train tracks");
        addWord("trains");
        addWord("trampoline");
        addWord("transformer");
        addWord("transport");
        addWord("transportation");
        addWord("trap");
        addWord("trash can");
        addWord("treadmill");
        addWord("treasure");
        addWord("treasure chest");
        addWord("tree");
        addWord("tree frog");
        addWord("treehouse");
        addWord("triangle");
        addWord("tricycle");
        addWord("triplets");
        addWord("trolley");
        addWord("trolls");
        addWord("trophy");
        addWord("trousers");
        addWord("truck");
        addWord("trumpet");
        addWord("tsunami");
        addWord("tub");
        addWord("tug of war");
        addWord("tuna");
        addWord("tunnel");
        addWord("turkey");
        addWord("turret");
        addWord("turtle");
        addWord("tuxedo");
        addWord("tweezers");
        addWord("twig");
        addWord("typewriter");
        addWord("tyre");
        addWord("umbrella");
        addWord("undead");
        addWord("under the sea");
        addWord("underwater");
        addWord("unicorn");
        addWord("unicycle");
        addWord("upside down");
        addWord("vacuum");
        addWord("valentine");
        addWord("vampire");
        addWord("van");
        addWord("vase");
        addWord("vault");
        addWord("vegetable garden");
        addWord("vegetables");
        addWord("vegetarian");
        addWord("vehicle");
        addWord("vending machine");
        addWord("venus fly trap");
        addWord("video camera");
        addWord("video game");
        addWord("viking");
        addWord("viking ship");
        addWord("village");
        addWord("villager");
        addWord("violin");
        addWord("volcano");
        addWord("volcano eruption");
        addWord("volcano erupting");
        addWord("voldemort");
        addWord("volleyball");
        addWord("voltage");
        addWord("vulture");
        addWord("waffle");
        addWord("wagon");
        addWord("walkie talkie");
        addWord("wall");
        addWord("wallet");
        addWord("walrus");
        addWord("wand");
        addWord("wardrobe");
        addWord("warrior");
        addWord("washing basket");
        addWord("washing machine");
        addWord("wasp");
        addWord("watch");
        addWord("water");
        addWord("water balloon");
        addWord("water bottle");
        addWord("water bucket");
        addWord("water park");
        addWord("water slide");
        addWord("water tap");
        addWord("waterfall");
        addWord("watering can");
        addWord("watermelon");
        addWord("waterski");
        addWord("waterslide");
        addWord("wave");
        addWord("weather");
        addWord("web");
        addWord("wedding");
        addWord("wedding cake");
        addWord("wedding ring");
        addWord("weightlifting");
        addWord("weights");
        addWord("well");
        addWord("wellies");
        addWord("werewolf");
        addWord("western");
        addWord("whale");
        addWord("wheat");
        addWord("wheel");
        addWord("wheelie");
        addWord("whirlpool");
        addWord("whistle");
        addWord("whiteboard");
        addWord("wig");
        addWord("wild west");
        addWord("wind");
        addWord("wind turbine");
        addWord("windmill");
        addWord("window");
        addWord("window cleaner");
        addWord("wine");
        addWord("wings");
        addWord("wink");
        addWord("winter");
        addWord("wire");
        addWord("wishing well");
        addWord("witch");
        addWord("witch house");
        addWord("wither");
        addWord("wizard");
        addWord("wizard hat");
        addWord("wolf");
        addWord("wool");
        addWord("workshop");
        addWord("world");
        addWord("worm");
        addWord("wrecking ball");
        addWord("wrapping paper");
        addWord("wrench");
        addWord("wrestling");
        addWord("writing");
        addWord("xylophone");
        addWord("yacht");
        addWord("yellow brick road");
        addWord("yoghurt");
        addWord("youtube");
        addWord("zebra");
        addWord("zelda");
        addWord("zeus");
        addWord("zip line");
        addWord("zipper");
        addWord("zombie");
        addWord("zombie apocalypse");
        addWord("zoo");
        addWord("egg");
        addWord("firetruck");
        addWord("flower");
        addWord("hippo");
        addWord("keyboard");
        addWord("monster");
        addWord("motorcycle");
        addWord("pac-man");
        addWord("pancakes");
        addWord("pirates");
        addWord("pokémon");
        addWord("shoe");
        addWord("spooky tree");
        addWord("tea cup");
        addWord("the sun");
        addWord("train");
        addWord("yeti");
        addWord("movie theater");
        addWord("wing");
        addWord("mitten");
        addWord("mobile phone");
        addWord("race car");
        addWord("rollerblades");
        addWord("speaker");
        addWord("landry basket");
        addWord("moterbike");
        addWord("gold course");
        addWord("ores");
        addWord("stoplight");
        addWord("omelet");
        addWord("bycicle");
        addWord("graduation cap");
        addWord("pickel");
        addWord("gold fish");
        addWord("flippers");
        addWord("dance floor");
        addWord("deadtree");
        addWord("phonecharger");
        addWord("yogurt");
        addWord("playing cardsalien");
    }

    public static void addWord(String word) {
    	
    	int length = word.length();
    	
    	if(!words.containsKey(length))
    		words.put(length, new ArrayList<String>());
    	
    	words.get(length).add(word);
    	return;
    }
}
